apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- nexus_editor_role.yaml
- nexus_viewer_role.yaml
