apiVersion: redhatgov.io/v1alpha1
kind: Nexus
metadata:
  name: nexus-sample
spec:
  nexus:
    expose:
      ssl: true                           # There is currently no way to specify an alternate certificate
      uri: nexus-sample.example.com   # You can leave this field out on OpenShift to get the default
      kind: Ingress                       # This can be of kind Route on OpenShift (the default)
    image:
      src: registry.connect.redhat.com/sonatype/nexus-repository-manager
      tag: latest
      pullPolicy: Always
    volumeSize: 10Gi
    oauth:
      enabled: true
      adminUsers:
      - openshift-admin
  persistent: true
