apiVersion: redhatgov.io/v1alpha1
kind: Nexus
metadata:
  name: nexus-testing
spec:
  nexus:
    expose:
      ssl: false
      kind: Ingress
      uri: localhost
      oauth: false
    resources:
      cpu:
        request: 500m
        limit: 1000m
  persistent: false
