apiVersion: redhatgov.io/v1alpha1
kind: Nexus
metadata:
  name: nexus-sample
spec:
  postgresql:
    volumeSize: 1Gi
    image:
      src: postgres
      tag: '10'
  nexus:
    expose:
      ssl: true                           # There is currently no way to specify an alternate certificate
      uri: nexus-sample.example.com   # You can leave this field out on OpenShift to get the default
      kind: Ingress                       # This can be of kind Route on OpenShift (the default)
    image:
      src: registry.connect.redhat.com/sonatype/nexus-repository-manager
      tag: latest
      pullPolicy: Always
    volumeSize: 1Gi
  persistent: true
