---
- name: Check for Nexus CR object
  k8s_info:
    api_version: redhatgov.io/v1alpha1
    namespace: "{{ _nexus_namespace }}"
    kind: Nexus
  register: nexus_cr_object

- set_fact:
    nexus_name: "{{ nexus_cr_object.resources[0].metadata.name }}"
  when: nexus_cr_object.resources

- fail:
    msg: "Nexus CR does not exist. Please create Nexus CR service."
  when: nexus_name is undefined

- name: Verify that nexus application is available
  when:
  - _nexus_name is defined
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    name: "{{ nexus_name }}"
    namespace: "{{ _nexus_namespace }}"
  register: r_deployment
  until:
  - r_deployment.resources[0].status.availableReplicas is defined
  - r_deployment.resources[0].status.availableReplicas == 1
  retries: 50
  delay: 10

- name: Check for admin credential secret
  k8s_info:
    namespace: "{{ _nexus_namespace }}"
    kind: Secret
    name: "{{ nexus_name }}-admin-credentials"
  register: nexus_admin_credentials
  when: nexus_name is defined

- set_fact:
    nexus_admin_password: "{{ nexus_admin_credentials.resources[0].data.password | b64decode }}"
  when: nexus_admin_credentials.resources

- fail:
    msg: "Nexus admin password is undefined, retry later."
  when: nexus_admin_password is undefined
