---
# Tasks file for Nexus
- name: Set OpenShift objects for Nexus to {{ _nexus_state }}
  k8s:
    state: "{{ _nexus_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
  - service_account.yml.j2
  - service.yml.j2
  - deployment.yml.j2

- name: Set Nexus Ingress/Route to {{ _nexus_state }}
  when: item != 'None'
  k8s:
    state: "{{ _nexus_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item + '.yml.j2') | from_yaml }}"
  loop:
  - '{{ _nexus_expose_method }}'

- name: Set PersistentVolumeClaim for Nexus to {{ _nexus_state }}
  when: _nexus_persistent|bool
  k8s:
    state: "{{ _nexus_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', 'persistent_volume_claim.yml.j2') | from_yaml }}"

- name: Wait until application is available
  when:
  - _nexus_state == "present"
  - _nexus_wait_for_init|bool
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    name: "{{ _nexus_name }}"
    namespace: "{{ _nexus_namespace }}"
  register: r_deployment
  until:
  - r_deployment.resources[0].status.availableReplicas is defined
  - r_deployment.resources[0].status.availableReplicas == 1
  retries: 50
  delay: 10
  ignore_errors: yes
