---
# Persistent nexus deployment playbook.

# The following variables come from the ansible-operator
# - ansible_operator_meta.namespace
# - ansible_operator_meta.name (from the name of the CR)

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up Nexus
    include_role:
      name: ./roles/nexus-ocp
    vars:
      _nexus_namespace: "{{ ansible_operator_meta.namespace }}"
      _nexus_name: "{{ nexus_service_name | default(ansible_operator_meta.name) }}"

      _nexus_expose_method: "{{ nexus.expose.kind | default('Route') }}"
      _nexus_expose_uri: "{{ nexus.expose.uri | default('') }}"
      _nexus_ssl: "{{ nexus.expose.ssl | default(True) }}"

      _nexus_image: "{{ nexus.image.src | default('registry.connect.redhat.com/sonatype/nexus-repository-manager') }}"
      _nexus_image_tag: "{{ nexus.image.tag | default('latest') }}"
      _nexus_image_pull_policy: "{{ nexus.image.pullPolicy | default('IfNotPresent') }}"

      _nexus_persistent: "{{ persistent | default(True) }}"
      _nexus_volume_size: "{{ nexus.volumeSize | default('10Gi') }}"

      _nexus_memory_request: "{{ nexus.resources.memory.request | default('4Gi') }}"
      _nexus_memory_limit: "{{ nexus.resources.memory.limit | default('4Gi') }}"
      _nexus_cpu_request: "{{ nexus.resources.cpu.request | default(1) }}"
      _nexus_cpu_limit: "{{ nexus.resources.cpu.limit | default(4) }}"
