apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: nexus-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys and manages Nexus Reposiory Manager.
  displayName: Nexus Operator
  icon:
  - base64data: "PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDIwMDEwOTA0Ly9FTiIKICJodHRwOi8vd3d3LnczLm9yZy9UUi8yMDAxL1JFQy1TVkctMjAwMTA5MDQvRFREL3N2ZzEwLmR0ZCI+CjxzdmcgdmVyc2lvbj0iMS4wIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiB3aWR0aD0iMjgwLjAwMDAwMHB0IiBoZWlnaHQ9IjI4MC4wMDAwMDBwdCIgdmlld0JveD0iMCAwIDI4MC4wMDAwMDAgMjgwLjAwMDAwMCIKIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaWRZTWlkIG1lZXQiPgoKPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMDAwMDAsMjgwLjAwMDAwMCkgc2NhbGUoMC4xMDAwMDAsLTAuMTAwMDAwKSIKZmlsbD0iIzAwMDAwMCIgc3Ryb2tlPSJub25lIj4KPHBhdGggZD0iTTEzNzUgMjM5NyBjLTExIC04IC00NyAtMjkgLTgwIC00NyAtMzMgLTE4IC03NiAtNDMgLTk1IC01NSAtMTkgLTEyCi02MCAtMzYgLTkwIC01MyAtMzAgLTE2IC0xNzIgLTk3IC0zMTUgLTE4MCBsLTI2MCAtMTQ5IC0zIC01MDkgLTIgLTUwOSAyMgotMTUgYzEzIC04IDY4IC00MCAxMjMgLTcxIDU1IC0zMSAxNzUgLTEwMCAyNjcgLTE1MyA5MSAtNTMgMTcwIC05NiAxNzYgLTk2IDcKMCAxMjMgMTQwIDE0NSAxNzcgNSA3IC0zNSAzNiAtMTE1IDgzIC02OCA0MCAtMTU5IDkzIC0yMDMgMTIwIC00NCAyNiAtOTkgNTcKLTEyMiA2OSBsLTQzIDIxIDAgMzY5IDAgMzY4IDI3IDE0IGMxNSA4IDEwMCA1NiAxODggMTA3IDI1MiAxNDcgMzgwIDIyMSAzOTcKMjI3IDE1IDYgNjAgLTE5IDQwMyAtMjE3IDcyIC00MSAxNTQgLTg3IDE4MyAtMTAyIDM4IC0xOSA1MiAtMzIgNTIgLTQ3IDAgLTE2CjE0IC00IDU1IDQ3IDMxIDM4IDY5IDg2IDg2IDEwNyAzOCA0NiA1NiAyOSAtMTkxIDE3MyAtMTAyIDYwIC0yMjMgMTMwIC0yNzAKMTU4IC0xNDQgODQgLTI5MSAxNjcgLTMwMyAxNzIgLTcgMiAtMjEgLTIgLTMyIC05eiIvPgo8L2c+Cjwvc3ZnPgo="
    mediatype: "image/svg"
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redhatgov
  - nexus
  - devsecops
  links:
  - name: Nexus
    url: https://www.sonatype.com/product-nexus-repository
  - name: Nexus Operator
    url: https://github.com/andykrohg/nexus-operator
  maintainers:
  - email: akrohg@redhat.com
    name: Andy Krohg
  maturity: alpha
  provider:
    name: RedHatGov
    url: redhatgov.io
  version: 0.0.0
