apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: nexus.redhatgov.io
spec:
  group: redhatgov.io
  names:
    kind: Nexus
    listKind: NexusList
    plural: nexus
    singular: nexus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Nexus is the Schema for the nexus API
        properties:
          apiVersion:
            description: |
              APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |
              Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Nexus
            properties:
              nexus:
                description: Defines the desired state of the Nexus Deployment
                properties:
                  expose:
                    description: Defines the ways in which Nexus should be exposed
                    properties:
                      kind:
                        description: The kind of resource to use to expose Nexus
                        enum:
                        - Route
                        - Ingress
                        - None
                        type: string
                        default: Route
                      oauth:
                        description: Include a sidecar to leverage OpenShift OAuth
                        type: boolean
                        default: true
                      ssl:
                        description: Defines SSL/TLS state, if your IngressController/Router supports it
                        type: boolean
                        default: true
                      uri:
                        description: The URI that should be exposed for Nexus (do not include protocol)
                        pattern: ^[^{}/ :\\]+(?::\d+)?$
                        type: string
                    type: object
                  image:
                    description: Defines the ways in which the Nexus image should be sourced and managed
                    properties:
                      pullPolicy:
                        description: |
                          Defines the pullPolicy that should be applied to the image on the Deployment resource
                        enum:
                        - Always
                        - IfNotPresent
                        - Never
                        type: string
                        default: IfNotPresent
                      src:
                        description: Defines the registry source and image name for the Nexus image
                        type: string
                      tag:
                        description: Defines the specific tag to use for the Nexus image
                        type: string
                    type: object
                  resources:
                    description: Defines the resource constraints that should apply to Nexus
                    properties:
                      cpu:
                        description: Defines the CPU constraints that should apply to Nexus
                        properties:
                          limit:
                            description: How much CPU, measured in cores or millicores, should Nexus be limited to
                            pattern: ^[0-9]+m?$
                            type: string
                            default: 200m
                          request:
                            description: |
                              How much CPU, measured in cores or millicores, should Nexus be expected to always
                              have access to
                            pattern: ^[0-9]+m?$
                            type: string
                            default: 500m
                        type: object
                      memory:
                        description: Defines the memory constraints that should apply to Nexus
                        properties:
                          limit:
                            description: How much memory, measured in bytes, should Nexus be limited to
                            pattern: ^[0-9]+[EPTGMK]?i?$
                            type: string
                            default: 512Mi
                          request:
                            description: |
                              How much memory, measured in bytes, should Nexus be expected to always have access to
                            pattern: ^[0-9]+[EPTGMK]?i?$
                            type: string
                            default: 512Mi
                        type: object
                    type: object
                  volumeSize:
                    description: |
                      Defines the size of the volume, measured in bytes, that should be requested for Nexus's data
                      directory
                    pattern: ^[0-9]+[EPTGMK]?i?$
                    type: string
                    default: 10Gi
                type: object
              persistent:
                description: |
                  Defines whether your Nexus instance should retain state when the Pods are
                  terminated and restarted
                type: boolean
            type: object
          status:
            description: Status defines the observed state of Nexus
            properties:
              conditions:
                description: The conditions reported by the Ansible operator
                items:
                  properties:
                    ansibleResult:
                      description: The result reported from the last playbook run
                      properties:
                        changed:
                          description: The number of tasks that resulted in a change
                          type: integer
                        completion:
                          description: The time of completion
                          type: string
                        failures:
                          description: The number of tasks that failed
                          type: integer
                        ok:
                          description: The number of tasks that completed without change
                          type: integer
                        skipped:
                          description: The number of tasks that were skipped
                          type: integer
                      type: object
                    lastTransitionTime:
                      description: The last time the playbook was invoked following a watch
                      format: date-time
                      type: string
                    message:
                      description: The last message reported from the Ansible Operator SDK
                      type: string
                    reason:
                      description: The reason the status was updated
                      type: string
                    status:
                      description: The boolean return value of the playbook execution, as a string
                      type: string
                    type:
                      description: The type of status change event
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
